add csrf to blocks template
LUKKIEN/wagtailformblocks pull request #6
Opened 2016-10-24 14:04 UTC by OktayAltay

2016-10-24 14:09 UTC, mikedingjan requested changes

2016-10-24 14:09 UTC, mikedingjan commented on setup.py
> +    'django-request-provider==1.0.2',
Uit de docs: "You shouldn't be using this project. But you should be using the real one which is" https://pypi.python.org/pypi/django-contrib-requestprovider/1.0.1

2016-10-24 14:09 UTC, mikedingjan commented on wagtailformblocks/blocks.py
This newline can be removed (ln. 8)

2016-10-24 14:10 UTC, mikedingjan commented
Can you please tell me why this is needed? as far as I know the request is available for blocks from wagtail 1.6 up, so we should just be able to output the csrf_token with the {% csrf_token %} template tag.

2016-10-24 14:23 UTC, OktayAltay commented
We are getting csrf_token error when we post the form. That it is missing the token

2016-10-24 15:07 UTC, jjanssen commented
@mikedingjan that is not the case. When using the templatetag it doesn't render anything and [this](https://docs.djangoproject.com/en/1.10/ref/csrf/#ajax) is not a reliable situation.

2016-10-25 06:21 UTC, mikedingjan commented
I get that, still think that using the template tag from a "request context" should work normally, that request context will be available when using `{% include_block %}` http://docs.wagtail.io/en/v1.7/topics/streamfield.html#template-rendering as far as I can see from the docs it should work like that.

However, if this is not the case a solution should definitely be found, in my opinion implementing a package that says in its own docs `You shouldn't be using this project` isn't the right way to go.

2016-10-25 06:30 UTC, tleguijt commented
I agree with Mike.
When I tested it in a project the ``csrf_token`` was correctly rendered. If it's not, the problem might be that the ``RequestContext`` is missing?

And probably you don't need the ``csrf_token`` for this implementation anyway.
One ticket that is still open is #1 . When this is fixed it should be possible to use the form with a normal ``POST`` action from within the page itself.
Right now the only option is to handle the form submit in javascript and perform an ajax request to the server.
With this you could either;

- read the value that is rendered by ``{% csrf_token %}``
- read the CSRF token from the cookie as displayed here https://docs.djangoproject.com/en/1.10/ref/csrf/#ajax

We should not introduce another dependency, definitely not one that says ``You shouldn't be using this project``

2016-10-25 07:16 UTC, OktayAltay commented
Thanks, @mikedingjan i added the {% include_block %} to the template that was rendering my formblock and it worked.

2016-10-25 07:16 UTC, closed without merging